"""add assistant detail fields

Revision ID: 4b115e573fc0
Revises: 4f4d4a3c4c2e
Create Date: 2026-09-15 00:04:21.803440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b115e573fc0'
down_revision: Union[str, Sequence[str], None] = '4f4d4a3c4c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('additional_info', sa.String(length=1000), server_default='', nullable=False))
    op.add_column('assistants', sa.Column('max_concurrent_calls', sa.Integer(), server_default='1', nullable=False))
    op.add_column('assistants', sa.Column('minutes_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'minutes_used')
    op.drop_column('assistants', 'max_concurrent_calls')
    op.drop_column('assistants', 'additional_info')
    # ### end Alembic commands ###
